services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=3000 # Edit as needed (edit the port in dockerfile too)
    ports:
      - "3000:3000" # Expose the app on port 3000, edit as needed(edit the port in dockerfile too)
    volumes:
      - .:/app
    command: ["bun", "start"]
